### ISSUE TITLE
Investigate/fix IllegalCharacterError

### ISSUE THREAD

**Issue by alycejenni** [NaturalHistoryMuseum/ckanext-versioned-datastore#128] opened 2023-10-05 17:24 UTC
Figure out what's going on here: https://data.nhm.ac.uk/status/download/83eaf278-f7c8-467c-b6ba-fe1e9dda3de9

And fix it.

**Comment by jrdh** [comment] 2023-11-24 16:04
This is caused by this line in the openpyxl lib: https://foss.heptapod.net/openpyxl/openpyxl/-/blob/2.5.4/openpyxl/cell/cell.py#L69 so this implies there is some data in the Zoology records which has illegal characters. Next job is to find them and then presumably open a new issue on the data importer which removes them? Or, I guess, get them fixed at source in EMu if possible. I'm just downloading a full ZOO dump in csv format from the Portal and will report back once I've found the problematic characters.

**Comment by jrdh** [comment] 2023-11-24 16:57
Found it! It's the `locality` field in this record: https://data.nhm.ac.uk/object/889d42f7-a961-416e-8778-9db1822cf048. The value is `Miteme Mikouania Village, Miteme Mikouania Village, between Wagny Village and Lolo R., Forêt des Abeilles, route écounomique 0°38'S 12°22'E` but the first `°` has a `\x07` before it. We could put something into the xlsx downloader to cope with this but I'm more inclined to prevent any funky characters from getting into the Portal all together so this needs to be fixed in the data importer/splitgill/importing code in this extension.

**Comment by jrdh** [comment] 2023-11-24 17:09
Bonus detail: this `\x07` character is the [bell](https://www.compart.com/en/unicode/U+0007) character which you can produce by opening a terminal and pressing `ctrl-g` as described in the [wikipedia article](https://en.wikipedia.org/wiki/Bell_character#Usage). 

My bet is that the user was attempting to copy and paste the `°` from somewhere into the source field in EMu and accidentally hit `ctrl-g` instead of `ctrl-v` (they are close together!), and then correctly hit `ctrl-v` on the second attempt. This would explain the existence of the bell character and perhaps explain why it's only in front of the first `°`, not the second one (they made the mistake once, but not the second time). SUCH FUN.

**Comment by jrdh** [comment] 2023-11-24 19:47
Closing this as investigation complete, will fix in https://github.com/NaturalHistoryMuseum/splitgill/issues/15

**Closed by jrdh** 2023-11-24 19:47 UTC
Labels: bug
